apiVersion: email.mailerlite.com/v1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: mailerlite-operator
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-sample
spec:
  # TODO(user): Add fields here
