apiVersion: email.mailerlite.com/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: mailerlite-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-mailgun
spec:
  senderConfigRef: "emailsenderconfig-mailgun"
  recipientEmail: "erickcezar.oliveira@gmail.com"
  subject: "Teste email operator"
  body: "Oi Erick, esse é um teste funcional"
---
apiVersion: email.mailerlite.com/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: mailerlite-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-mailersent
spec:
  senderConfigRef: "emailsenderconfig-mailersent"
  recipientEmail: "erickcezar.oliveira@gmail.com"
  subject: "Teste email operator"
  body: "Oi Erick, esse é um teste funcional"